name: "Auto compile luci-app-simple2fa"

on:
  push:
    branches: [main, master]
    tags:
      - 'v*'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  # 定义插件包名，方便全局替换
  PKG_NAME: luci-app-simple2fa
  # 定义源码仓库地址
  REPO_URL: https://github.com/findnr/findnr-feeds

jobs:
  build_packages:
    name: Build [${{ matrix.target.platform }}]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - platform: "x86_64"
            sdk_url: "https://downloads.openwrt.org/releases/22.03.7/targets/x86/64/openwrt-sdk-22.03.7-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
          - platform: "aarch64_generic"
            sdk_url: "https://downloads.openwrt.org/releases/22.03.7/targets/rockchip/armv8/openwrt-sdk-22.03.7-rockchip-armv8_gcc-11.2.0_musl.Linux-x86_64.tar.xz"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential libncurses-dev gawk git gettext libssl-dev xsltproc zip zlib1g-dev file zstd rsync python3-pyelftools lua5.1

      - name: Download OpenWrt SDK
        run: |
          wget -q ${{ matrix.target.sdk_url }}
          file_name=$(basename ${{ matrix.target.sdk_url }})
          mkdir -p sdk
          tar -xf $file_name -C ./sdk --strip-components=1
          cd sdk
          # 添加 findnr-feeds 软件源
          echo "src-git findnr $REPO_URL" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure and Compile
        run: |
          cd $GITHUB_WORKSPACE/sdk
          
          # 刷新插件关联
          ./scripts/feeds install -a
          
          # 强行激活插件配置
          # 注意：simple2fa 可能依赖 google-authenticator-lib 或其他包，make defconfig 会自动处理
          echo "CONFIG_PACKAGE_${{ env.PKG_NAME }}=m" > .config
          # 如果该插件有特定语言包，也可以一起勾选
          echo "CONFIG_LUCI_LANG_zh_Hans=y" >> .config 
          
          make defconfig
          
          # 检查 Makefile 是否真的存在于 SDK 中
          find package/feeds/ -name "${{ env.PKG_NAME }}"
          
          # 编译插件 (IGNORE_ERRORS=1 防止非致命错误中断)
          make package/feeds/findnr/${{ env.PKG_NAME }}/compile -j$(nproc) V=s IGNORE_ERRORS=1

      - name: Collect IPK
        run: |
          mkdir -p $GITHUB_WORKSPACE/release
          # 搜索生成的 IPK，包括依赖项（如 simple2fa 依赖的二进制文件）
          find $GITHUB_WORKSPACE/sdk/bin/packages -name "*simple2fa*.ipk" -exec cp {} $GITHUB_WORKSPACE/release/ \;
          # 同时也建议收集 findnr 的其他依赖 ipk，以防路由器上缺少依赖
          find $GITHUB_WORKSPACE/sdk/bin/packages -name "findnr*.ipk" -exec cp {} $GITHUB_WORKSPACE/release/ \;
          
          if [ -z "$(ls -A $GITHUB_WORKSPACE/release)" ]; then
            echo "错误: 未发现生成的 IPK 文件"
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKG_NAME }}-${{ matrix.target.platform }}
          path: ${{ github.workspace }}/release/*.ipk

      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/release/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
